apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: pbench-benchmark
  namespace: benchmark-operator
spec:
  clustername: maxusoptest
  workload:
    # cleanup: true
    name: pbench
    args:
      serviceip: false
      hostnetwork: false
      networkpolicy: false
      multus:
        enabled: false
      pin: true
      #
      # pin: true/false - default=false
      #    - true will run 'Pin' mode using 1 server (pin_server:) and 1 client (pin_clien:) nodes.
      #    - false will run 'Scale' mode. See colocate, density_range, node_range and step_size.
      pin_server: "ip-10-0-215-63"
      pin_client: "ip-10-0-215-63"
      samples: 1
      kind: pod
      pair: 1
      #
      # 'pair' sepcifies fixed number of client-server pairs for "Pin" mode,
      #  If 'pair' is NOT present, it will use 'density_range' which allows
      #  enumeration in addition to fixed number of pair.
      test_types:
        - stream
      protos:
        - tcp
      sizes:
        - 16384
      nthrs:
        - 1
      runtime: 30

      # The following variables are for 'Scale' mode.
      # The 'Scale' mode is activated when 'pin=false' or undefined.
      # The Scale mode params are: colocate, denstisy_range, node_range and step_size.
      #
      # colocate: true/false - default=false
      # density_range: [n, m] - default=[1,1]
      # node_range: [x, y]  - default=[1,1]
      # step_size: log2 - default=add1
      #   Valid step_size values are: addN or log2
      #   N can be any decimal number
      #   Enumeration examples:
      #      add1:  1,2,3,4 ,,,
      #      add2:  1,3,5,7 ...
      #      add10: 1,11,21,31 ...
      #      log2:  1,2,4,8,16,32 ,,,
      #
      # 'exclude_labels' specifies the list of ineligible worker nodes.
      # exclude_labels:  (OR conditional, every node that matches any of these labels is excluded)
      #    - "bad=true"
      #    - "fc640=true"

